export const toolOrder = [
  "read",
  "write",
  "edit",
  "apply_patch",
  "exec",
  "process",
  "ls",
  "grep",
  "find",
  "browser",
  "canvas",
  "nodes",
  "cron",
  "message",
  "tts",
  "gateway",
  "agents_list",
  "sessions_list",
  "sessions_history",
  "sessions_send",
  "sessions_spawn",
  "session_status",
  "web_search",
  "web_fetch",
  "memory_search",
  "image",
];

export const coreToolSummaries: Record<string, string> = {
  read: "Read file contents",
  write: "Write files",
  edit: "Edit files",
  apply_patch: "Apply multi-file patches",
  exec: "Run shell commands",
  process: "Manage background commands",
  ls: "List directory contents",
  grep: "Search file contents for patterns",
  find: "Find files by glob pattern",
  browser: "Control the browser",
  canvas: "Present or snapshot the canvas",
  nodes: "Interact with paired nodes",
  cron: "Schedule cron jobs and wake events",
  message: "Send messages and channel actions",
  tts: "Text to speech",
  gateway: "Call gateway admin actions",
  agents_list: "List agents",
  sessions_list: "List sessions",
  sessions_history: "Fetch session history",
  sessions_send: "Send a message to another session",
  sessions_spawn: "Spawn a sub-agent session",
  session_status: "Show model and usage status",
  web_search: "Search the web",
  web_fetch: "Fetch web content",
  memory_search: "Search memory",
  image: "Generate or transform images",
};
